name: check
env:
  TZ: "Asia/Tokyo"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Update npm
        run: npm install -g npm
      - name: install packages
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm test
