name: release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Show environment
        run: set -x; pwd; ls -la; node -v; npm -v;
      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Set AuthToken for npmjs.com
        run: echo "//registry.npmjs.org/:_authToken=${NPM_ACCESS_TOKEN}" > "${HOME}/.npmrc"
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Update package version
        run: |
          npm version ${{ github.event.inputs.bump_type }}
          echo VERSION="v$(cat package.json | jq -r '.version')" >> "${GITHUB_ENV}"
#      - name: Publish to npmjs.com
#        run: |
#          npm ci
#          npm run release
      - name: Push tag to GitHub
        run: |
          git push
          git push --tags
#      - name: Create Release to GitHub
#        run: |
#          gh release create "${VERSION}" --generate-notes
