name: update_static_files

on:
  schedule:
    - cron: "15 11 20 * *" # UTC
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Update static files
        run: "./.github/scripts/update_static_files.sh"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Update static files"
          commit-message: "Update static files"
          branch: "update-static-files"
          delete-branch: true
          branch-suffix: timestamp
          reviewers: mryhryki
