name: update_dependencies

on:
  schedule:
    - cron: "15 11 20 * *" # UTC
  workflow_dispatch:

jobs:
  update_dependencies:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write
    steps:
      - uses: Kesin11/actions-timeline@v2
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Update packages
        run: |
          npm i -g npm
          npm exec -- npm-check-updates -u
          npm install
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Update dependencies"
          commit-message: "Update dependencies"
          branch: "update-dependencies"
          delete-branch: true
          branch-suffix: timestamp
          assignees: mryhryki
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
